services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0
